In [1]:
from sqlalchemy import create_engine, text
import pandas as pd

database_url = "postgresql://etl_user:Zw56jAa5y6Zhp5hioIDelHMyHx8wrAmj@dpg-d6qu8qc50q8c73bpfi40-a.oregon-postgres.render.com/etl_seguros_xmv0"
engine = create_engine(database_url)

with engine.connect() as conn:
    conn.execute(text("SELECT 1"))
    conn.commit()

print("Conexión exitosa")

Conexión exitosa

In [2]:
# Total de pólizas
pd.read_sql("""
SELECT COUNT(*) AS total_polizas
FROM polizas_curated;
""", engine)

   total_polizas
0           3634

In [3]:
# Pólizas por aseguradora
pd.read_sql("""
SELECT id_aseguradora, COUNT(*) AS cantidad_polizas
FROM polizas_curated
GROUP BY id_aseguradora;
""", engine)

    id_aseguradora  cantidad_polizas
0                4               226
1               14               221
2                3               263
3               10               230
4                9               236
5                7               264
6               13               255
7                1               236
8                5               269
9                2               250
10              15               238
11               6               238
12              12               217
13               8               223
14              11               268

In [4]:

# Siniestros por estado
pd.read_sql("""
SELECT estado, COUNT(*) AS cantidad_siniestros
FROM siniestros_curated
GROUP BY estado;
""", engine)

      estado  cantidad_siniestros
0    Cerrado                  231
1    Abierto                  204
2  Rechazado                   99

In [5]:
# Total monto siniestros
pd.read_sql("""
SELECT SUM(monto_siniestro) AS total_monto_siniestros
FROM siniestros_curated;
""", engine)

   total_monto_siniestros
0            3.057913e+06