In [1]:
import pandas as pd

In [2]:
url_siniestros = "https://raw.githubusercontent.com/BAcost26/etl-data-pipeline/refs/heads/main/data/raw/siniestros.csv"

df = pd.read_csv(url_siniestros)

df.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

In [3]:
# Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

id_siniestro          0
id_poliza             0
fecha_siniestro       0
monto_siniestro     616
estado             1298
dtype: int64

In [4]:
#limpieza de datos
siniestros = df.copy()

siniestros.columns = siniestros.columns.str.strip().str.lower()

for col in siniestros.select_dtypes(include='object').columns:
    siniestros[col] = siniestros[col].astype(str).str.strip()

siniestros = siniestros.replace(r'^\s*$', pd.NA, regex=True)
siniestros = siniestros.replace("nan", pd.NA)
siniestros = siniestros.replace("-", pd.NA)

# Normalizar estado
siniestros['estado'] = siniestros['estado'].replace({
    'ABIERTO': 'Abierto',
    'abierto': 'Abierto',
    'cerrado': 'Cerrado',
    'CERRADO': 'Cerrado',
    'rechazado': 'Rechazado',
    'RECHAZADO': 'Rechazado'
})

# Convertir fecha con dayfirst=True por formatos tipo 16-10-2025 y 01/08/2025
siniestros['fecha_siniestro'] = pd.to_datetime(
    siniestros['fecha_siniestro'],
    errors='coerce',
    dayfirst=True
)

# Limpiar monto_siniestro
siniestros['monto_siniestro'] = (
    siniestros['monto_siniestro']
    .astype(str)
    .str.replace(",", "", regex=False)
)

siniestros['monto_siniestro'] = siniestros['monto_siniestro'].replace("nan", pd.NA)
siniestros['monto_siniestro'] = pd.to_numeric(siniestros['monto_siniestro'], errors='coerce')

# Eliminar duplicados
siniestros = siniestros.drop_duplicates()

siniestros.head()

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0             1      17400      2025-10-16          2092.59    Abierto
1             2       2465             NaT          7076.25    Abierto
2             3      15785      2025-09-19           702.27    Cerrado
3             4      14299             NaT           274.63    Abierto
4             5      12908             NaT          9377.69  Rechazado

In [5]:
#verificar columnas reales
print(siniestros.columns)

Index(['id_siniestro', 'id_poliza', 'fecha_siniestro', 'monto_siniestro',
       'estado'],
      dtype='object')

In [6]:
#Separar válidos y rechazados
validos = siniestros[
    siniestros['id_siniestro'].notna() &
    siniestros['id_poliza'].notna() &
    siniestros['fecha_siniestro'].notna() &
    siniestros['monto_siniestro'].notna() &
    siniestros['estado'].notna()
].copy()

rechazados = siniestros[
    siniestros['id_siniestro'].isna() |
    siniestros['id_poliza'].isna() |
    siniestros['fecha_siniestro'].isna() |
    siniestros['monto_siniestro'].isna() |
    siniestros['estado'].isna()
].copy()

In [7]:
def motivo(row):
    motivos = []

    if pd.isna(row['id_siniestro']):
        motivos.append("id_siniestro_vacio")
    if pd.isna(row['id_poliza']):
        motivos.append("id_poliza_vacio")
    if pd.isna(row['fecha_siniestro']):
        motivos.append("fecha_siniestro_invalida")
    if pd.isna(row['monto_siniestro']):
        motivos.append("monto_siniestro_invalido")
    if pd.isna(row['estado']):
        motivos.append("estado_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [8]:
print("\n✅ Válidos:")
print(validos)
print("\n❌ Rechazados con motivos:")
print(rechazados[['id_siniestro','id_poliza','fecha_siniestro','monto_siniestro','estado','motivo_rechazo']])

✅ Válidos:
      id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0                1      17400      2025-10-16          2092.59    Abierto
2                3      15785      2025-09-19           702.27    Cerrado
7                8      23824      2025-01-17          2736.20    Abierto
12              13       3716      2025-07-13         -4274.39  Rechazado
23              24      17180      2025-06-13          6183.83    Cerrado
...            ...        ...             ...              ...        ...
4579          4580      23259      2025-01-20          5724.16    Cerrado
4583          4584       5850      2025-01-01           745.06    Cerrado
4586          4587      20874      2025-01-29          5212.81    Cerrado
4606          4607      12631      2025-04-16         11965.15  Rechazado
4619          4620      10815      2025-10-11         14958.46    Abierto

[534 rows x 5 columns]

❌ Rechazados con motivos:
      id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado  \
1                2       2465             NaT          7076.25    Abierto
3                4      14299             NaT           274.63    Abierto
4                5      12908             NaT          9377.69  Rechazado
5                6       5107             NaT         10535.74       <NA>
6                7       3379             NaT         10513.30    Abierto
...            ...        ...             ...              ...        ...
4614          4615       3466             NaT              NaN       <NA>
4615          4616      12223             NaT          5806.47       <NA>
4616          4617       3953             NaT         14622.50    Cerrado
4617          4618      10239             NaT              NaN    Abierto
4618          4619      18897             NaT           354.26       <NA>

                                         motivo_rechazo
1                              fecha_siniestro_invalida
3                              fecha_siniestro_invalida
4                              fecha_siniestro_invalida
5                 fecha_siniestro_invalida,estado_vacio
6                              fecha_siniestro_invalida
...                                                 ...
4614  fecha_siniestro_invalida,monto_siniestro_inval...
4615              fecha_siniestro_invalida,estado_vacio
4616                           fecha_siniestro_invalida
4617  fecha_siniestro_invalida,monto_siniestro_invalido
4618              fecha_siniestro_invalida,estado_vacio

[4086 rows x 6 columns]

In [9]:
validos.to_csv("siniestros_curated.csv", index=False)
rechazados.to_csv("siniestros_rejects.csv", index=False)

In [10]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 49.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [11]:
from sqlalchemy import create_engine, text
import pandas as pd

database_url = "postgresql://etl_user:Zw56jAa5y6Zhp5hioIDelHMyHx8wrAmj@dpg-d6qu8qc50q8c73bpfi40-a.oregon-postgres.render.com/etl_seguros_xmv0"

engine = create_engine(database_url)

with engine.connect() as conn:
    conn.execute(text("SELECT 1"))
    conn.commit()

print("Conexión exitosa")

Conexión exitosa

In [12]:
sql_create_curated = """
CREATE TABLE IF NOT EXISTS siniestros_curated (
    id_siniestro INT PRIMARY KEY,
    id_poliza INT,
    fecha_siniestro DATE,
    monto_siniestro FLOAT,
    estado VARCHAR(50)
);
"""

with engine.connect() as conn:
    conn.execute(text(sql_create_curated))
    conn.commit()

print("Tabla siniestros_curated creada")

Tabla siniestros_curated creada

In [13]:
sql_create_rejects = """
CREATE TABLE IF NOT EXISTS siniestros_rejects (
    id_siniestro INT,
    id_poliza INT,
    fecha_siniestro DATE,
    monto_siniestro FLOAT,
    estado VARCHAR(50),
    motivo_rechazo VARCHAR(200)
);
"""

with engine.connect() as conn:
    conn.execute(text(sql_create_rejects))
    conn.commit()

print("Tabla siniestros_rejects creada")

Tabla siniestros_rejects creada

In [14]:
validos.to_sql(
    'siniestros_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'siniestros_rejects',
    engine,
    if_exists='append',
    index=False
)

print("Datos cargados correctamente")

Datos cargados correctamente

In [15]:
pd.read_sql("SELECT * FROM siniestros_curated LIMIT 10", engine)

   id_siniestro  id_poliza fecha_siniestro  monto_siniestro     estado
0             1      17400      2025-10-16       2092.59000    Abierto
1             3      15785      2025-09-19        702.27000    Cerrado
2             8      23824      2025-01-17       2736.20000    Abierto
3            13       3716      2025-07-13      -4274.39000  Rechazado
4            24      17180      2025-06-13       6183.83000    Cerrado
5            33       2231      2025-09-21       2443.90000  Rechazado
6            36      16929      2025-01-06       3649.94000    Cerrado
7            45      15100      2025-01-27       8761.24000    Abierto
8            66      14064      2025-03-25       9842.05000    Abierto
9            67       5049      2025-05-26         13.72301  Rechazado

In [16]:
pd.read_sql("SELECT * FROM siniestros_rejects LIMIT 10", engine)

,id_siniestro,id_poliza,fecha_siniestro,monto_siniestro,estado,motivo_rechazo
0,2,2465,None,7076.25000,Abierto,fecha_siniestro_invalida
1,4,14299,None,274.63000,Abierto,fecha_siniestro_invalida
2,5,12908,None,9377.69000,Rechazado,fecha_siniestro_invalida
3,6,5107,None,10535.74000,None,"fecha_siniestro_invalida,estado_vacio"
4,7,3379,None,10513.30000,Abierto,fecha_siniestro_invalida
5,9,18118,None,NaN,Cerrado,"fecha_siniestro_invalida,monto_siniestro_invalido"
6,10,19947,None,8801.03000,Cerrado,fecha_siniestro_invalida
7,11,6448,None,1.61938,Abierto,fecha_siniestro_invalida
8,12,4096,None,NaN,Rechazado,"fecha_siniestro_invalida,monto_siniestro_invalido"
9,14,8260,None,NaN,None,"fecha_siniestro_invalida,monto_siniestro_inval..."

In [17]:
dayfirst=True