In [1]:
import pandas as pd

In [2]:
url_polizas = "https://raw.githubusercontent.com/BAcost26/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"

df = pd.read_csv(url_polizas)

df.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

In [3]:
# Exploración de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB

id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

In [5]:
# limpieza de datos
polizas = df.copy()

polizas.columns = polizas.columns.str.strip().str.lower()

for col in polizas.select_dtypes(include='object').columns:
    polizas[col] = polizas[col].astype(str).str.strip()

polizas = polizas.replace(r'^\s*$', pd.NA, regex=True)
polizas = polizas.replace("nan", pd.NA)
polizas = polizas.replace("-", pd.NA)

# Convertir fecha
polizas['fecha_emision'] = pd.to_datetime(polizas['fecha_emision'], errors='coerce')

# Limpiar números con comas y puntos
for col in ['prima', 'comision', 'monto_asegurado']:
    polizas[col] = (
        polizas[col]
        .astype(str)
        .str.replace(" ", "", regex=False)
        .str.replace(".", "", regex=False)
        .str.replace(",", ".", regex=False)
    )
    polizas[col] = polizas[col].replace("nan", pd.NA)
    polizas[col] = pd.to_numeric(polizas[col], errors='coerce')

# eliminar duplicados
polizas = polizas.drop_duplicates()

polizas.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaT,184,42,15,2,829.53,NaN,1.392531e+07
1,2,2026-02-16,2408,35,11,12,NaN,12.22,2.754432e+04
2,3,NaT,540,42,4,9,161153.00,92.05,1.732984e+02
3,4,NaT,2821,40,10,5,186662.00,45699.00,2.444613e+07
4,5,NaT,945,23,9,11,NaN,324.08,1.234078e+07

In [6]:
validos = polizas[
    polizas['id_poliza'].notna() &
    polizas['fecha_emision'].notna() &
    polizas['id_cliente'].notna() &
    polizas['id_corredor'].notna() &
    polizas['id_aseguradora'].notna() &
    polizas['id_tipo_seguro'].notna() &
    polizas['monto_asegurado'].notna()
].copy()

rechazados = polizas[
    polizas['id_poliza'].isna() |
    polizas['fecha_emision'].isna() |
    polizas['id_cliente'].isna() |
    polizas['id_corredor'].isna() |
    polizas['id_aseguradora'].isna() |
    polizas['id_tipo_seguro'].isna() |
    polizas['monto_asegurado'].isna()
].copy()

In [7]:
def motivo(row):
    motivos = []

    if pd.isna(row['id_poliza']):
        motivos.append("id_poliza_vacio")
    if pd.isna(row['fecha_emision']):
        motivos.append("fecha_emision_invalida")
    if pd.isna(row['id_cliente']):
        motivos.append("id_cliente_vacio")
    if pd.isna(row['id_corredor']):
        motivos.append("id_corredor_vacio")
    if pd.isna(row['id_aseguradora']):
        motivos.append("id_aseguradora_vacio")
    if pd.isna(row['id_tipo_seguro']):
        motivos.append("id_tipo_seguro_vacio")
    if pd.isna(row['monto_asegurado']):
        motivos.append("monto_asegurado_invalido")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [9]:
print("\n✅ Válidos:")
print(validos)
print("\n❌ Rechazados con motivos:")
print(rechazados[['id_poliza','fecha_emision','id_cliente','id_corredor','id_aseguradora','id_tipo_seguro','monto_asegurado','motivo_rechazo']])

✅ Válidos:
       id_poliza fecha_emision  id_cliente  id_corredor  id_aseguradora  \
1              2    2026-02-16        2408           35              11
9             10    2026-01-24        2281           69              13
25            26    2025-07-29        2295           71              11
30            31    2025-08-07        1847           45               4
44            45    2025-12-11        2278           66               3
...          ...           ...         ...          ...             ...
25118      25119    2025-11-02        2655          116               6
25124      25125    2026-01-10        1589           62              11
25126      25127    2025-03-02          18           80              15
25138      25139    2025-06-07        2312           20              15
25144      25145    2025-05-18        1250           61               8

       id_tipo_seguro      prima  comision  monto_asegurado
1                  12        NaN     12.22     2.754432e+04
9                   3   79138.00     67.44     2.071000e+06
25                  4   61446.00    149.78     3.667097e+06
30                  2        NaN    229.13     1.173099e+05
44                 11  153937.00  24041.00     1.147323e+02
...               ...        ...       ...              ...
25118               5  -41435.00   8485.00     1.905014e+04
25124               5    1107.94  18723.00     1.764081e+02
25126               7  104634.00    126.62     1.188335e+02
25138               4   35612.00     21.98     3.065368e+06
25144               8   77417.00   5866.00     1.135580e+02

[3634 rows x 9 columns]

❌ Rechazados con motivos:
       id_poliza fecha_emision  id_cliente  id_corredor  id_aseguradora  \
0              1           NaT         184           42              15
2              3           NaT         540           42               4
3              4           NaT        2821           40              10
4              5           NaT         945           23               9
5              6           NaT        1295           17               1
...          ...           ...         ...          ...             ...
25145      25146           NaT        2328           27               3
25146      25147    2025-07-02        2295           16               1
25147      25148           NaT         133           48              10
25148      25149           NaT        2221           29              13
25149      25150           NaT        3676           54               1

       id_tipo_seguro  monto_asegurado            motivo_rechazo
0                   2     1.392531e+07    fecha_emision_invalida
2                   9     1.732984e+02    fecha_emision_invalida
3                   5     2.444613e+07    fecha_emision_invalida
4                  11     1.234078e+07    fecha_emision_invalida
5                   1     7.196843e+06    fecha_emision_invalida
...               ...              ...                       ...
25145               6     3.772476e+07    fecha_emision_invalida
25146               9              NaN  monto_asegurado_invalido
25147               4     6.915630e+05    fecha_emision_invalida
25148               3     1.697661e+07    fecha_emision_invalida
25149               8     3.104200e+05    fecha_emision_invalida

[21516 rows x 8 columns]

In [10]:
validos.to_csv("polizas_curated.csv", index=False)
rechazados.to_csv("polizas_rejects.csv", index=False)

In [11]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 34.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [12]:
from sqlalchemy import create_engine, text
import pandas as pd

database_url = "postgresql://etl_user:Zw56jAa5y6Zhp5hioIDelHMyHx8wrAmj@dpg-d6qu8qc50q8c73bpfi40-a.oregon-postgres.render.com/etl_seguros_xmv0"

engine = create_engine(database_url)

with engine.connect() as conn:
    conn.execute(text("SELECT 1"))
    conn.commit()

print("Conexión exitosa")

Conexión exitosa

In [13]:
sql_create_curated = """
CREATE TABLE IF NOT EXISTS polizas_curated (
    id_poliza INT PRIMARY KEY,
    fecha_emision DATE,
    id_cliente INT,
    id_corredor INT,
    id_aseguradora INT,
    id_tipo_seguro INT,
    prima FLOAT,
    comision FLOAT,
    monto_asegurado FLOAT
);
"""

with engine.connect() as conn:
    conn.execute(text(sql_create_curated))
    conn.commit()

print("Tabla polizas_curated creada")

Tabla polizas_curated creada

In [14]:
sql_create_rejects = """
CREATE TABLE IF NOT EXISTS polizas_rejects (
    id_poliza INT,
    fecha_emision DATE,
    id_cliente INT,
    id_corredor INT,
    id_aseguradora INT,
    id_tipo_seguro INT,
    prima FLOAT,
    comision FLOAT,
    monto_asegurado FLOAT,
    motivo_rechazo VARCHAR(200)
);
"""

with engine.connect() as conn:
    conn.execute(text(sql_create_rejects))
    conn.commit()

print("Tabla polizas_rejects creada")

Tabla polizas_rejects creada

In [15]:
validos.to_sql(
    'polizas_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'polizas_rejects',
    engine,
    if_exists='append',
    index=False
)

print("Datos cargados correctamente")

Datos cargados correctamente

In [16]:
pd.read_sql("SELECT * FROM polizas_curated LIMIT 10", engine)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,2,2026-02-16,2408,35,11,12,NaN,12.22,2.754432e+04
1,10,2026-01-24,2281,69,13,3,79138.0,67.44,2.071000e+06
2,26,2025-07-29,2295,71,11,4,61446.0,149.78,3.667097e+06
3,31,2025-08-07,1847,45,4,2,NaN,229.13,1.173099e+05
4,45,2025-12-11,2278,66,3,11,153937.0,24041.00,1.147323e+02
5,48,2025-07-16,259,29,14,1,NaN,4688.00,5.568851e+06
6,49,2025-08-11,1122,2,14,4,33732.0,6959.00,4.721014e+06
7,50,2025-02-22,717,49,15,10,51878.0,86.45,6.687199e+04
8,66,2025-03-04,1352,21,12,6,77633.0,14721.00,1.128291e+07
9,73,2025-03-01,841,26,7,12,NaN,NaN,3.302390e+01

In [17]:
pd.read_sql("SELECT * FROM polizas_rejects LIMIT 10", engine)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado,motivo_rechazo
0,1,None,184,42,15,2,829.53,NaN,1.392531e+07,fecha_emision_invalida
1,3,None,540,42,4,9,161153.00,92.05,1.732984e+02,fecha_emision_invalida
2,4,None,2821,40,10,5,186662.00,45699.00,2.444613e+07,fecha_emision_invalida
3,5,None,945,23,9,11,NaN,324.08,1.234078e+07,fecha_emision_invalida
4,6,None,1295,17,1,1,94349.00,NaN,7.196843e+06,fecha_emision_invalida
5,7,None,1254,25,11,4,140082.00,18840.00,2.582029e+07,fecha_emision_invalida
6,8,None,887,77,3,8,167056.00,25875.00,NaN,"fecha_emision_invalida,monto_asegurado_invalido"
7,9,None,1670,66,8,12,NaN,131.85,1.258048e+07,fecha_emision_invalida
8,11,None,2590,25,8,4,NaN,NaN,NaN,"fecha_emision_invalida,monto_asegurado_invalido"
9,12,None,1521,14,11,5,72602.00,NaN,8.621665e+06,fecha_emision_invalida