In [1]:
import pandas as pd

In [2]:
url_corredores = "https://raw.githubusercontent.com/BAcost26/etl-data-pipeline/refs/heads/main/data/raw/corredores.csv"

df = pd.read_csv(url_corredores)

df.head()

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

In [9]:
df.shape
df.info()
df.isnull().sum()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               63 non-null     object
 3   nivel              68 non-null     object
 4   anios_experiencia  76 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 3.3+ KB

Index(['id_corredor', 'nombre', 'zona', 'nivel', 'anios_experiencia'], dtype='object')

In [10]:
corredores = df.copy()

# Normalizar nombres de columnas
corredores.columns = corredores.columns.str.strip().str.lower()

# Limpiar strings
for col in corredores.select_dtypes(include='object').columns:
    corredores[col] = corredores[col].astype(str).str.strip()

# Reemplazar vacíos
corredores = corredores.replace(r'^\s*$', pd.NA, regex=True)
corredores = corredores.replace("nan", pd.NA)

# Quitar duplicados
corredores = corredores.drop_duplicates()

corredores.head()

   id_corredor               nombre         zona   nivel  anios_experiencia
0            1    José López Flores  Paracentral     Mid                4.0
1            2    José Ortiz García       Centro  Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                6.0
3            4  Fernanda Rojas Cruz         <NA>  SENIOR                8.0
4            5      Ana Gómez Rojas         <NA>  Senior                4.0

In [11]:
validos = corredores[
    corredores['id_corredor'].notna() &
    corredores['nombre'].notna() &
    corredores['zona'].notna() &
    corredores['nivel'].notna() &
    corredores['anios_experiencia'].notna()
].copy()

rechazados = corredores[
    corredores['id_corredor'].isna() |
    corredores['nombre'].isna() |
    corredores['zona'].isna() |
    corredores['nivel'].isna() |
    corredores['anios_experiencia'].isna()
].copy()

In [12]:
def motivo(row):
    motivos = []

    if pd.isna(row['id_corredor']):
        motivos.append("id_corredor_vacio")

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['zona']):
        motivos.append("zona_vacia")

    if pd.isna(row['nivel']):
        motivos.append("nivel_vacio")

    if pd.isna(row['anios_experiencia']):
        motivos.append("anios_experiencia_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [13]:
print("\n✅ Válidos:")
print(validos)
print("\n❌ Rechazados con motivos:")
print(rechazados[['id_corredor', 'nombre', 'zona', 'nivel', 'anios_experiencia', 'motivo_rechazo']])

✅ Válidos:
    id_corredor                       nombre         zona   nivel  \
0             1            José López Flores  Paracentral     Mid
1             2            José Ortiz García       Centro  Junior
2             3           María Ramírez Cruz       Centro  SENIOR
5             6        Sofía Reyes Hernández    Occidente   Elite
7             8        Paula Ortiz Hernández       Centro  Junior
8             9        Carlos Torres Vásquez  Paracentral  junior
12           13        Valeria García Torres      Oriente  SENIOR
13           14           Diego Gómez Chávez       Centro  Senior
15           16           Juan Reyes Morales        Costa  Junior
17           18           Paula Pérez Flores      Oriente     Mid
18           19        Fernanda Ortiz Flores       Centro  SENIOR
21           22         Andrés Torres García       Centro   Elite
22           23         Paula Mendoza Flores       Centro  junior
24           25          Andrés Gómez Chávez       Centro  junior
26           27        Carlos Mendoza Torres  Paracentral     Mid
27           28         Carmen Ortiz Mendoza       Centro  SENIOR
29           30         Carlos Cruz Martínez  Paracentral  SENIOR
30           31         María Aguilar García      Oriente     Mid
31           32          Ricardo Ortiz Gómez        Costa  SENIOR
32           33          Karla Rojas Ramírez  Paracentral  junior
34           35           Diego García Reyes       Centro  SENIOR
35           36            Diego Santos Cruz       Centro  Junior
37           38           María Mendoza Cruz        Costa  junior
39           40        Ricardo Rojas Ramírez    Occidente  Junior
40           41         Andrés Vásquez Rojas       Centro   Elite
41           42      Juan Hernández Martínez       Centro  junior
42           43            José Cruz Ramírez  Paracentral  SENIOR
43           44             Luis Rojas Gómez        Costa   Elite
44           45           María Chávez Ortiz    Occidente  Junior
45           46        Fernanda López García  Paracentral     Mid
46           47      Ricardo Aguilar Ramírez       Centro  Junior
49           50      Carlos Ramírez Martínez       Centro  junior
52           53          María Torres García  Paracentral   Elite
53           54            Jorge Cruz Santos       Centro  SENIOR
55           56            Marta Cruz Flores       Centro     Mid
56           57          Carlos Chávez Reyes    Occidente  Junior
57           58       Karla Santos Hernández    Occidente  SENIOR
61           62  Fernanda Castillo Hernández      Oriente  Senior
62           63             José Ortiz Pérez        Costa  Senior
63           64          Sofía Reyes Ramírez        Costa  SENIOR
65           66             Juan López Reyes      Oriente  junior
66           67          Carmen Chávez Ortiz       Centro  SENIOR
68           69            Jorge Ortiz Pérez       Centro     Mid
70           71      Diego Hernández Vásquez       Centro  SENIOR
71           72              Luis Cruz Gómez      Oriente   Elite
72           73           Carmen Reyes Rojas  Paracentral  Senior
74           75       Paula Vásquez Castillo  Paracentral     Mid
77           78         Fernanda Reyes López    Occidente  Senior
78           79        Jorge Flores Martínez    Occidente  SENIOR
79           80            Pedro Reyes Rojas    Occidente   Elite

    anios_experiencia
0                 4.0
1                 0.0
2                 6.0
5                 3.0
7                17.0
8                 2.0
12               23.0
13               20.0
15                6.0
17               23.0
18               12.0
21               19.0
22               23.0
24               23.0
26               11.0
27               10.0
29                2.0
30               21.0
31               99.0
32                9.0
34               17.0
35               22.0
37               15.0
39               21.0
40               99.0
41               10.0
42               14.0
43                7.0
44               20.0
45               13.0
46                5.0
49               10.0
52                3.0
53                2.0
55               21.0
56               14.0
57                6.0
61                3.0
62               19.0
63               15.0
65                8.0
66                0.0
68                1.0
70               23.0
71                0.0
72                5.0
74                0.0
77                5.0
78               13.0
79               18.0

❌ Rechazados con motivos:
    id_corredor                   nombre       zona   nivel  \
3             4      Fernanda Rojas Cruz       <NA>  SENIOR
4             5          Ana Gómez Rojas       <NA>  Senior
6             7     Pedro Vásquez Torres      Costa    <NA>
9            10       Juan Cruz Castillo  Occidente    <NA>
10           11      José Morales Flores       <NA>  junior
11           12      Pedro Gómez Vásquez       <NA>     Mid
14           15      Fernanda Cruz Reyes     Centro     Mid
16           17      Jorge Reyes Ramírez       <NA>   Elite
19           20         Pedro Cruz Pérez       <NA>  Junior
20           21     Juan Hernández Pérez    Oriente    <NA>
23           24        José Ortiz Flores       <NA>  Junior
25           26    Valeria Mendoza Gómez  Occidente    <NA>
28           29  Ricardo López Hernández       <NA>    <NA>
33           34     Lucía Vásquez Chávez       <NA>  Junior
36           37         Juan Cruz García     Centro    <NA>
38           39        Sofía Ortiz Pérez       <NA>     Mid
47           48      Lucía López Morales      Costa    <NA>
48           49     Paula Castillo Rojas       <NA>     Mid
50           51     Juan Martínez Santos       <NA>  SENIOR
51           52   Daniela Gómez Martínez  Occidente    <NA>
54           55     Andrés Santos Santos       <NA>  Senior
58           59     Daniela Flores Pérez       <NA>  Junior
59           60     Pedro Castillo Gómez       <NA>    <NA>
60           61    Carlos Torres Mendoza     Centro  junior
64           65  Valeria Martínez García     Centro    <NA>
67           68        José García Pérez     Centro    <NA>
69           70  Carlos Vásquez Martínez       <NA>     Mid
73           74    José Morales Martínez       <NA>     Mid
75           76      Sofía Morales Reyes      Costa    <NA>
76           77  Valeria Vásquez Mendoza     Centro  junior

    anios_experiencia                      motivo_rechazo
3                 8.0                          zona_vacia
4                 4.0                          zona_vacia
6                 1.0                         nivel_vacio
9                 7.0                         nivel_vacio
10                NaN  zona_vacia,anios_experiencia_vacio
11               21.0                          zona_vacia
14                NaN             anios_experiencia_vacio
16               20.0                          zona_vacia
19               24.0                          zona_vacia
20               21.0                         nivel_vacio
23                9.0                          zona_vacia
25               20.0                         nivel_vacio
28               25.0              zona_vacia,nivel_vacio
33                7.0                          zona_vacia
36               10.0                         nivel_vacio
38               25.0                          zona_vacia
47               25.0                         nivel_vacio
48                6.0                          zona_vacia
50               99.0                          zona_vacia
51                5.0                         nivel_vacio
54                6.0                          zona_vacia
58                7.0                          zona_vacia
59               17.0              zona_vacia,nivel_vacio
60                NaN             anios_experiencia_vacio
64                8.0                         nivel_vacio
67               11.0                         nivel_vacio
69               21.0                          zona_vacia
73                6.0                          zona_vacia
75                2.0                         nivel_vacio
76                NaN             anios_experiencia_vacio

In [14]:
validos.to_csv("corredores_curated.csv", index=False)
rechazados.to_csv("corredores_rejects.csv", index=False)

In [15]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 40.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [17]:
from sqlalchemy import create_engine, text
import pandas as pd

database_url = "postgresql://etl_user:Zw56jAa5y6Zhp5hioIDelHMyHx8wrAmj@dpg-d6qu8qc50q8c73bpfi40-a.oregon-postgres.render.com/etl_seguros_xmv0"

engine = create_engine(database_url)

with engine.connect() as conn:
    conn.execute(text("SELECT 1"))
    conn.commit()

print("Conexión exitosa")

Conexión exitosa

In [18]:
sql_create_curated = """
CREATE TABLE IF NOT EXISTS corredores_curated (
    id_corredor INT PRIMARY KEY,
    nombre VARCHAR(150),
    zona VARCHAR(100),
    nivel VARCHAR(50),
    anios_experiencia FLOAT
);
"""

with engine.connect() as conn:
    conn.execute(text(sql_create_curated))
    conn.commit()

print("Tabla corredores_curated creada")

Tabla corredores_curated creada

In [19]:
sql_create_rejects = """
CREATE TABLE IF NOT EXISTS corredores_rejects (
    id_corredor INT,
    nombre VARCHAR(150),
    zona VARCHAR(100),
    nivel VARCHAR(50),
    anios_experiencia FLOAT,
    motivo_rechazo VARCHAR(200)
);
"""

with engine.connect() as conn:
    conn.execute(text(sql_create_rejects))
    conn.commit()

print("Tabla corredores_rejects creada")

Tabla corredores_rejects creada

In [20]:
validos.to_sql(
    'corredores_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'corredores_rejects',
    engine,
    if_exists='append',
    index=False
)

print("Datos cargados correctamente")

Datos cargados correctamente

In [21]:
pd.read_sql("SELECT * FROM corredores_curated LIMIT 10", engine)

   id_corredor                 nombre         zona   nivel  anios_experiencia
0            1      José López Flores  Paracentral     Mid                4.0
1            2      José Ortiz García       Centro  Junior                0.0
2            3     María Ramírez Cruz       Centro  SENIOR                6.0
3            6  Sofía Reyes Hernández    Occidente   Elite                3.0
4            8  Paula Ortiz Hernández       Centro  Junior               17.0
5            9  Carlos Torres Vásquez  Paracentral  junior                2.0
6           13  Valeria García Torres      Oriente  SENIOR               23.0
7           14     Diego Gómez Chávez       Centro  Senior               20.0
8           16     Juan Reyes Morales        Costa  Junior                6.0
9           18     Paula Pérez Flores      Oriente     Mid               23.0

In [22]:
pd.read_sql("SELECT * FROM corredores_rejects LIMIT 10", engine)

,id_corredor,nombre,zona,nivel,anios_experiencia,motivo_rechazo
0,4,Fernanda Rojas Cruz,None,SENIOR,8.0,zona_vacia
1,5,Ana Gómez Rojas,None,Senior,4.0,zona_vacia
2,7,Pedro Vásquez Torres,Costa,None,1.0,nivel_vacio
3,10,Juan Cruz Castillo,Occidente,None,7.0,nivel_vacio
4,11,José Morales Flores,None,junior,NaN,"zona_vacia,anios_experiencia_vacio"
5,12,Pedro Gómez Vásquez,None,Mid,21.0,zona_vacia
6,15,Fernanda Cruz Reyes,Centro,Mid,NaN,anios_experiencia_vacio
7,17,Jorge Reyes Ramírez,None,Elite,20.0,zona_vacia
8,20,Pedro Cruz Pérez,None,Junior,24.0,zona_vacia
9,21,Juan Hernández Pérez,Oriente,None,21.0,nivel_vacio